modLoader = "javafml"
loaderVersion = "[4,)"
license = "${modLicense}"
issueTrackerURL = "${modIssueTracker}"

[[mods]]
    modId = "${modId}"
    version = "${modVersion}"
    displayName = "${modName}"
    authors = "${modAuthors}"
    description = '''${modDescription}'''

[[dependencies.${modId}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neoForgeVersionRange}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${modId}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraftVersionRange}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${modId}]]
    modId = "tfc"
    type = "required"
    versionRange = "${tfcVersionRange}"
    ordering = "AFTER"
    side = "BOTH"

[[mixins]]
    config = "${modId}.mixins.json"
