org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=tfcmorefloorstorage
mod_name=TFC More Floor Storage
mod_license=MIT
mod_version=0.1.0-experiment
mod_group_id=com.minerguy341.tfcmorefloorstorage
mod_authors=minerguy341
mod_description=Experimental TFC addon for manipulating ingot pile mesh rendering toward denser floor storage.

# CurseForge file id for TerraFirmaCraft-Forge-1.20.1-3.2.23
tfc_curse_file=8242625
patchouli_version=1.20.1-84-FORGE
mixin_version=0.8.5
